# eshopwebmvc-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopwebmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshopwebmvc
  template:
    metadata:
      labels:
        app: eshopwebmvc
    spec:
      containers:
      - image: ghcr.io/noesis-devops/eshoponweb-mvc:main
        name: eshopwebmvc
        ports:
        - containerPort: 80
