apiVersion: v1
kind: Service
metadata:
  name: eshoppublicapi
spec:
  selector:
    app: eshoppublicapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Change this line to expose it as NodePort
