# postgresql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "someThingComplicated1234"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "mydatabase"
      # Add other configurations like environment variables, volumes, etc. if needed