name: .NET Tests
 
on:
  push:
    branches:
      - TST
  # pull_request:
  #  branches:
  #    - main
 
jobs:
  build-and-test:
    runs-on: windows-ra
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build Functional Tests
        run: dotnet build tests/FunctionalTests/FunctionalTests.csproj --configuration Release -p:NoWarn=NU1605
        
      - name: Run Unit Tests
        run: dotnet test tests/UnitTests/UnitTests.csproj --configuration Release --no-build --logger "trx;LogFileName=unit.trx"
 
      - name: Run Integration Tests
        run: dotnet test tests/IntegrationTests/IntegrationTests.csproj --configuration Release --no-build --logger "trx;LogFileName=integration.trx"
 
      - name: Run Functional Tests
        run: dotnet test tests/FunctionalTests/FunctionalTests.csproj --configuration Release --no-build --logger "trx;LogFileName=functional.trx"
 
      - name: Run Public API Integration Tests (ignorar conflitos de pacote)
        run: dotnet build tests/PublicApiIntegrationTests/PublicApiIntegrationTests.csproj --configuration Release
 
  deploy:
    runs-on: windows-ra
    needs: build-and-test
    if: success()
    steps:
      - name: Deploy step
        run: echo "Deploying application..."
