name: .NET Tests
on:
  push:
    branches:
      - TST
jobs:
  build-and-test:
    runs-on: windows-ra
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build maven
        run: mvn -B compile --file pom.xml

      - name: Run Functional Tests
        run: dotnet test tests/FunctionalTests/FunctionalTests.csproj --configuration Release --logger "trx;LogFileName=functional.trx" --logger "console;verbosity=detailed" -v minimal
        
      - name: Run Unit Tests
        run: dotnet test tests/UnitTests/UnitTests.csproj --configuration Release --logger "trx;LogFileName=unit.trx" --logger "console;verbosity=detailed" -v minimal
 
      - name: Run Integration Tests
        run: dotnet test tests/IntegrationTests/IntegrationTests.csproj --configuration Release --logger "trx;LogFileName=integration.trx" --logger "console;verbosity=detailed" -v minimal

      - name: Run Public API Integration Tests (ignorar conflitos de pacote)
        run: dotnet test tests/PublicApiIntegrationTests/PublicApiIntegrationTests.csproj --configuration Release --logger "trx;LogFileName=publicapi.trx" --logger "console;verbosity=detailed" -v minimal

      - name: Run E2E tests (LoginTest and ProductTest)
        run: mvn -B test -Dtest="e2e.tests.LoginTest,e2e.tests.ProductTest"
        
  deploy:
    runs-on: windows-ra
    needs: build-and-test
    if: success()
    steps:
      - name: Deploy step
        run: echo "Deploying application..."
